### ISSUE TITLE
Reverse out (1 if on and 0 if off)

### ISSUE THREAD

**Issue by meppe** [kwindrem/RpiGpioSetup#12]
Hi, 
is it somehow possible to reverse the output, i.e., set to high when ON and low when OFF? The default is the other way around, and I am unable to see the logic behind this. Maybe my thoughts took a wrong turn anyhow... 

For example, I have an electric battery heating connected via GPIO+relay to be turned on if the temp is low. When I shut off the Raspi, I don't want the heating to run, no matter what the temperature is...  Any tips on how to work around this? 
I am quite used to coding, and I played around a bit with https://github.com/kwindrem/RpiGpioSetup/blob/main/VenusGpioOverlay.dts but did not manage to use it for my purposes.

Yes, I saw the following sentence in the README: "Relays that activate on a low signal are NOT COMPATIBLE since the relays would still close during Raspberry PI boot regardless of the logic provided by Venus OS." But I still wonder if there is a way to get around this... 

Thanks a lot for all your work, @kwindrem , I really appreciate it! 

Manfred

**Comment by kwindrem** [comment]
The problem is the GPIO output defaults defined within the hardware itself. It is possible to reverse the pins with a DT overlay, this code is not executed until part way through the boot process. This means the relays would close until the system boots, at least partially.
