### ISSUE TITLE
temperature control rule page just empty/white

### ISSUE THREAD

**Issue by sergios100** [kwindrem/RpiGpioSetup#15]
Hi Kevin,

me and an other user on the victron forum [https://community.victronenergy.com/questions/189232/guimods-relais-temperature.html?childToView=190233#answer-190233](url) just ran into an issue with the "Relay" page. When "temperature" is assigned to Relay 2 an additional line " Temperature control rules" appears, as expected: 

<img width="789" alt="Bildschirm­foto 2023-03-02 um 18 38 01" src="https://user-images.githubusercontent.com/63123058/222508394-14feeb24-a74d-4f37-938a-7dc75bbc0675.png">

When this is selected though, it just show's a white page, nothing to set up there:

<img width="789" alt="Bildschirm­foto 2023-03-02 um 13 15 50" src="https://user-images.githubusercontent.com/63123058/222508868-6a85bbc6-a02e-49d5-b8f8-d1c786dca90c.png">

I set up a fresh v2.93 stock system on my Raspberry Pi 4 and added just your fine setup-helper and RPIGpioSetup:
<img width="789" alt="Bildschirm­foto 2023-03-02 um 18 30 52" src="https://user-images.githubusercontent.com/63123058/222509206-0025631f-77d8-47a0-b091-20261e6bd6e0.png">

Is there anything we are missing? I found some pictrures while googeling the internet, where this page is populated with settings like "activation value", "deactivation value" and "condition".

Any input much appreciated!

Sergio

**Comment by kwindrem** [comment]
I was able to reproduce the blank Temp rules page. This occurs if there are no temperature sensors OR if the temperature relay service is not running. This service will crash if the RpiTemperature package from TimD1981 is installed. I don't see this installed in your test screen shots above but maybe you didn't have any temp sensors attached.

Error: ValueError: Invalid object path '/Settings/TempSensorRelay/Rpi-cpu06/Enabled': contains invalid character '-'

It has nothing to do with GuiMods or RpiGpioSetup

I have posted in issue with the author of that package.
